[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
project_name = "CTer8F2vgzYMrEPz7RDwToKyhvsUfKrjugivWvQNeQsm"

[programs.devnet]
project_name = "CTer8F2vgzYMrEPz7RDwToKyhvsUfKrjugivWvQNeQsm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
